server:
  port: 5555

# http://localhost:5555/actuator/routes 访问服务映射表[其默认不暴露，故进行以下配置]
management:
  endpoints:
    web:
      exposure:
        include: routes

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**

# 黑名单，阻止Cookie,Set-Cookie的传播[如果不设置，zuul自动阻止Cookie,Set-Cookie,Authorization的传播]
zuul:
  sensitive-headers: Cookie,Set-Cookie
